name: build-doc-radar-api
channels: [conda-forge]
dependencies:
  - docutils
  - jupyter
  - nbsphinx==0.9.3
  - pandoc
  - pip
  - python>=3.10
  - sphinx-book-theme==1.1.0
  - sphinx-gallery
  - sphinx-mdinclude==0.5.3
  - sphinx==7.2.6
  - sphinxcontrib-youtube
  - radar-api
